SPOOL C:\DB2\project_part11\bonus_question2.txt
SELECT TO_CHAR (sysdate, 'Day DD Month Year HH:MI:SS Am') FROM dual;

-- Question 2:
-- (use script 7northwoods)
-- Create a view containing 
-- course name, credit, student name, c_sec_id, SEC NUM,
-- grade of all course section taken by a student.
CREATE OR REPLACE VIEW STUDENTS_COURSES_VIEW AS
SELECT C.COURSE_NAME, C.CREDITS, S.S_LAST, S.S_FIRST, CS.C_SEC_ID, CS.SEC_NUM, E.GRADE
FROM COURSE C, STUDENT S, COURSE_SECTION CS, ENROLLMENT E
WHERE CS.C_SEC_ID = E.C_SEC_ID
AND E.S_ID = S.S_ID
AND C.COURSE_ID = CS.COURSE_ID;


-- Can we UPDATE, INSERT directly TO the view?
-- If NOT, can you provide a solution?
SELECT * FROM STUDENTS_COURSES_VIEW;


-- UPDATE
UPDATE STUDENTS_COURSES_VIEW
SET GRADE = 'A'
WHERE S_LAST = 'Umato' AND C_SEC_ID = 1;
-- Update yes, we can.

-- INSERT
-- INSERT INTO STUDENTS_COURSES_VIEW VALUES ('Databases II', 2, 'Amaral', 'Ayrton', 8, 4, 'A'); 
-- As question 1 and the reasons mentioned, it is not possible to insert directly here.
-- The solution is also creating a Instead of Trigger.


-- INSTEAD OF TRIGGER SOLUTION:
DROP SEQUENCE STUDS_SEQUENCE;
CREATE SEQUENCE STUDS_SEQUENCE INCREMENT BY 1 START WITH 13;

DROP SEQUENCE COURSE_SEQUENCE;
CREATE SEQUENCE COURSE_SEQUENCE INCREMENT BY 1 START WITH 6;

DROP SEQUENCE CSECID_SEQUENCE;
CREATE SEQUENCE CSECID_SEQUENCE INCREMENT BY 1 START WITH 15;


CREATE OR REPLACE TRIGGER STUDENTS_COURSES_VIEW_TRIGGER
INSTEAD OF INSERT ON STUDENTS_COURSES_VIEW
FOR EACH ROW
BEGIN
    INSERT INTO COURSE (COURSE_ID, COURSE_NAME, CREDITS)
    VALUES (COURSE_SEQUENCE.NEXTVAL, :NEW.COURSE_NAME, :NEW.CREDITS);
    
    INSERT INTO STUDENT (S_ID, S_LAST, S_FIRST)
    VALUES (STUDS_SEQUENCE.NEXTVAL, :NEW.S_LAST, :NEW.S_FIRST);
    
    INSERT INTO COURSE_SECTION (C_SEC_ID, COURSE_ID, TERM_ID, SEC_NUM, MAX_ENRL)
    VALUES (CSECID_SEQUENCE.NEXTVAL, COURSE_SEQUENCE.CURRVAL, 6, :NEW.SEC_NUM, 30);
    
    INSERT INTO ENROLLMENT (S_ID, C_SEC_ID, GRADE)
    VALUES (STUDS_SEQUENCE.CURRVAL, CSECID_SEQUENCE.CURRVAL, :NEW.GRADE);    
END;
/


INSERT INTO STUDENTS_COURSES_VIEW VALUES ('Databases II', 2, 'Amaral', 'Ayrton', 8, 4, 'A'); 


SELECT * FROM STUDENTS_COURSES_VIEW;
-- Now, we can insert.


SPOOL OFF
